name: build to my blog

on:
  # 配置当push进入什么分支的时候执行
  push:
    branches: 
     - master

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # 具体的执行步骤
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

     # 使用的node版本   
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
      
     # 执行安装
      - name: Install dependencies
        run: npm install
    
    # 执行打包
      - name: Build Blog
        run: npm run build
      
    # 执行部署
      - name: Deploy to Pages
        run: |
          cd  docs/.vitepress/dist 
          git init
          git config user.name "wangkaibing"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git commit -m 'deploy'
          git push -f https://Kai-web:${{ secrets.ACCESS_TOKEN }}@github.com/Kai-web/Kai-web.github.io.git master:gh-pages
          cd -

    # 搜索
     algolia:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Get the content of algolia.json as config
          id: algolia_config
          run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"
        - name: Push indices to Algolia
          uses: signcl/docsearch-scraper-action@master
          env:
            APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
            API_KEY: ${{ secrets.ADMIN_API_KEY }}
            CONFIG: ${{ steps.algolia_config.outputs.config }}
